language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c "CREATE DATABASE narep_test;" -U postgres
script:
  - npm test
after_success:
  - 'npm run coveralls'